uploads = []
generated = []

[[outputs]]
id = "IFzMELSZu5XqonY6PPckb"
uri = "file://artifacts/galaxy-analyzer/galaxy-rotation-curve-analysis-full-report.txt"
type = "text"
title = "Galaxy Rotation Curve Analysis - Full Report"

[[outputs]]
id = "X5AT-26xbitRV5O4TxsBL"
uri = "file://artifacts/galaxy-analyzer/galaxy-rotation-curve-analysis-full-report.txt.gz"
type = "unspecified"
title = "Galaxy Rotation Curve Analysis - Full Report (Compressed)"
